import React from 'react';
// eslint-disable-next-line import/no-cycle
import BaseIcon from 'components/icons/BaseIcon';
import CastingIcon from './Casting';
import LandingPageIcon from './LandingPage';
import PhotoCompetitionIcon from './PhotoCompetition';
import RightPriceIcon from './RightPrice';
import PersonalityTestIcon from './PersonalityTest';
import ProductDesignerIcon from './ProductDesigner';
import ContestGameIcon from './ContestGame';
import SurveyIcon from './Survey';
import WinnerQuizIcon from './WinnerQuiz';
import QuizzIcon from './Quizz';
import BattleIcon from './Battle';
import FlapFlapIcon from './FlapFlap';
import BasketIcon from './Basket';
import FastCupIcon from './FastCup';
import ObjectHideIcon from './ObjectHide';
import PronosticGameIcon from './PronosticGame';
import BrickBreakerIcon from './BrickBreaker';
import PuzzleIcon from './Puzzle';
import PenaltyIcon from './Penalty';
import MemoryIcon from './Memory';
import MultiMechanicsIcon from './MultiMechanics';
import TwoThousandFortyEightIcon from './2048';
import WhaleAMoleIcon from './WhackAMole';
import DifferenceIcon from './Difference';
import CutcutIcon from './Cutcut';
import JumpjumpIcon from './Jumpjump';
import RunnerIcon from './Runner';
import Match3Icon from './Match3';
import JackpotIcon from './Jackpot';
import PinataIcon from './Pinata';
import ScratchIcon from './Scratch';
import WheelOfFortuneIcon from './WheelOfFortune';
import CalendarIcon from './Calendar';
import WinnerDiceIcon from './WinnerDice';
import InstantWinIcon from './InstantWin';
import CardFlipIcon from './CardFlip';
import GifWinIcon from './GifWin';
import SpaceSmashIcon from './SpaceSmash';

// eslint-disable-next-line react/jsx-filename-extension
export const Casting = (props) => <BaseIcon component={CastingIcon} {...props} />;
export const LandingPage = (props) => <BaseIcon component={LandingPageIcon} {...props} />;
export const PhotoCompetition = (props) => <BaseIcon component={PhotoCompetitionIcon} {...props} />;
export const RightPrice = (props) => <BaseIcon component={RightPriceIcon} {...props} />;
export const Quizz = (props) => <BaseIcon component={QuizzIcon} {...props} />;
export const PersonalityTest = (props) => <BaseIcon component={PersonalityTestIcon} {...props} />;
export const ProductDesigner = (props) => <BaseIcon component={ProductDesignerIcon} {...props} />;
export const ContestGame = (props) => <BaseIcon component={ContestGameIcon} {...props} />;
export const Survey = (props) => <BaseIcon component={SurveyIcon} {...props} />;
export const WinnerQuiz = (props) => <BaseIcon component={WinnerQuizIcon} {...props} />;
export const Battle = (props) => <BaseIcon component={BattleIcon} {...props} />;
export const FlapFlap = (props) => <BaseIcon component={FlapFlapIcon} {...props} />;
export const Basket = (props) => <BaseIcon component={BasketIcon} {...props} />;
export const FastCup = (props) => <BaseIcon component={FastCupIcon} {...props} />;
export const ObjectHide = (props) => <BaseIcon component={ObjectHideIcon} {...props} />;
export const PronosticGame = (props) => <BaseIcon component={PronosticGameIcon} {...props} />;
export const BrickBreaker = (props) => <BaseIcon component={BrickBreakerIcon} {...props} />;
export const Puzzle = (props) => <BaseIcon component={PuzzleIcon} {...props} />;
export const Penalty = (props) => <BaseIcon component={PenaltyIcon} {...props} />;
export const Memory = (props) => <BaseIcon component={MemoryIcon} {...props} />;
export const TwoThousandFortyEight = (props) => <BaseIcon component={TwoThousandFortyEightIcon} {...props} />;
export const MultiMechanics = (props) => <BaseIcon component={MultiMechanicsIcon} {...props} />;
export const WhaleAMole = (props) => <BaseIcon component={WhaleAMoleIcon} {...props} />;
export const Difference = (props) => <BaseIcon component={DifferenceIcon} {...props} />;
export const Cutcut = (props) => <BaseIcon component={CutcutIcon} {...props} />;
export const Runner = (props) => <BaseIcon component={RunnerIcon} {...props} />;
export const Jumpjump = (props) => <BaseIcon component={JumpjumpIcon} {...props} />;
export const Match3 = (props) => <BaseIcon component={Match3Icon} {...props} />;
export const Jackpot = (props) => <BaseIcon component={JackpotIcon} {...props} />;
export const Pinata = (props) => <BaseIcon component={PinataIcon} {...props} />;
export const Scratch = (props) => <BaseIcon component={ScratchIcon} {...props} />;
export const WheelOfFortune = (props) => <BaseIcon component={WheelOfFortuneIcon} {...props} />;
export const Calendar = (props) => <BaseIcon component={CalendarIcon} {...props} />;
export const WinnerDice = (props) => <BaseIcon component={WinnerDiceIcon} {...props} />;
export const InstantWin = (props) => <BaseIcon component={InstantWinIcon} {...props} />;
export const CardFlip = (props) => <BaseIcon component={CardFlipIcon} {...props} />;
export const GifWin = (props) => <BaseIcon component={GifWinIcon} {...props} />;
export const SpaceSmash = (props) => <BaseIcon component={SpaceSmashIcon} {...props} />;
